# permissions for end users to view instaslices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: instaslice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: instaslice-operator
    app.kubernetes.io/part-of: instaslice-operator
    app.kubernetes.io/managed-by: kustomize
  name: instaslice-viewer-role
rules:
- apiGroups:
  - inference.codeflare.dev
  resources:
  - instaslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.codeflare.dev
  resources:
  - instaslices/status
  verbs:
  - get
