---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - inference.codeflare.dev
  resources:
  - instaslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.codeflare.dev
  resources:
  - instaslices/finalizers
  verbs:
  - update
- apiGroups:
  - inference.codeflare.dev
  resources:
  - instaslices/status
  verbs:
  - get
  - patch
  - update
